services:
  # Runs the FiveM server w/ resources on local disk mounted as a volume.
  fivem:
    image: tsrp-fivem:latest
    build: .
    stdin_open: true
    tty: true
    ports:
      - "30120:30120/tcp"
      - "30120:30120/udp"
      - "40125:40125"
    volumes:
      - type: bind
        source: ./src
        target: /fivem/server-data/resources/[local]
      - type: bind
        source: ./data/txData
        target: /fivem/fxserver/txData
      - type: bind
        source: ./cfg
        target: /fivem/server-data/config
      - type: bind
        source: ./vendor
        target: /fivem/server-data/resources/[vendor]
  # This config is NOT suitable for running in production
  database:
    image: mariadb:10.8
    ports:
      - "3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_ROOT_HOST: localhost
      MARIADB_DATABASE: tsrp_fivem_development
      MARIADB_USER: tsrp
      MARIADB_PASSWORD: tsrpdev
    volumes:
      - type: bind
        source: ./data/gamedb
        target: /var/lib/mysql
  # Run this to compile all front-end assets across all resources.
  node:
    image: node:lts
    working_dir: /fivem
    command: /bin/bash /fivem/build/npm_build.sh
    tty: true
    volumes:
      - type: bind
        source: ./src
        target: /fivem/src
      - type: bind
        source: ./build
        target: /fivem/build