services:
  fivem:
    image: tsrp-fivem:latest
    build: .
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./server-data/resources
        target: /fivem/server-data/resources