services:
  fivem:
    image: tsrp-fivem:latest
    build: .
    stdin_open: true
    tty: true
    ports:
      - "30120"
      - "40125"
    volumes:
      - type: bind
        source: ./src
        target: /fivem/server-data/resources/[local]
      - type: bind
        source: ./cfx/txData
        target: /fivem/fxserver/txData