name: Build Release

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3

        with:
          node-version: '18.x'

      - run: npm ci
      - run: npm run build --workspaces

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: brice/tsrp-fivem:latest
